### ISSUE TITLE
Buttons aren't working 😕 

### ISSUE THREAD

**Issue by itsvks19** [folderv/androidDataWithoutRootAPI33#3]
These buttons are not working. 

![Screenshot_20220824-110857_Foo](https://user-images.githubusercontent.com/102840735/186338178-53ef9811-6d6d-49fb-9b53-067ab889b4ec.jpg)

**Comment by folderv** [comment]
this demo only works on Android 13 API 33

**Comment by itsvks19** [comment]
Fixed 😍

**Comment by itsvks19** [comment]
My android version is 12
